### ISSUE TITLE
Error - perhaps due to config?

### ISSUE THREAD

**Issue by bradydjohnson** [ijgnd/anki__rebuild-empty-all-filtered-decks#1]
Got this error. Could it be my config settings? How am I supposed to identify decks in the config?

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
> Debug info:
> Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
> Platform: Mac 10.15.4
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2020-05-26 16:08:28
> Add-ons possibly involved: ⁨rebuild allempty all filtered decks enhanced fork, Review Heatmap⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt/webview.py", line 34, in cmd
>   File "aqt/webview.py", line 114, in _onCmd
>   File "aqt/webview.py", line 518, in _onBridgeCmd
>   File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-114>", line 2, in _linkHandler
>   File "anki/hooks.py", line 638, in decorator_wrapper
>   File "anki/hooks.py", line 635, in repl
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/review_heatmap/links.py", line 74, in heatmapLinkHandler
>     return None if not _old else _old(self, url)
>   File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-4>", line 2, in _linkHandler
>   File "anki/hooks.py", line 638, in decorator_wrapper
>   File "anki/hooks.py", line 630, in repl
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/104518886/RebuildAll.py", line 92, in _handleFilteredDeckButtons
>     _updateFilteredDecks(url)
>   File "/Users/bradyjohnson/Library/Application Support/Anki2/addons21/104518886/RebuildAll.py", line 66, in _updateFilteredDecks
>     if deck and deck.id in dynDeckIds:
> AttributeError: 'dict' object has no attribute 'id'

Config
```
{
    "build - prioritize most nested subdecks": true,
    "build first": [
        "AnKing : 1) Learning Today"
    ],
    "build last": [
        "AnKing : 9) Backlog"
    ]
}
```
My decks
<img width="239" alt="Brady - Anki 2020-05-27 00-36-44" src="https://user-images.githubusercontent.com/6741590/82981688-3b883a00-9fb2-11ea-83d1-1161ba68c265.png">

**Comment by ijgnd** [comment]
Thanks for the report. You found a bug. I uploaded a new version to ankiweb. Could you update and try again and let me know if you still have problems. So far I only needed the feature "build - prioritize most nested subdecks" so I missed the bug.
