### ISSUE TITLE
Error in 2.1.45beta5

### ISSUE THREAD

**Issue by AnKingMed** [ijgnd/anki__rebuild-empty-all-filtered-decks#3]
Getting an error as mentioned [here](https://forums.ankiweb.net/t/anki-2-1-45-beta/10664/76?u=ankingmed)

> File “/Users/Nick/Library/Application Support/Anki2/addons21/104518886/RebuildAll.py”, line 148, in
> Card.flushSched = wrap(Card.flushSched, postSched)
> AttributeError: type object ‘Card’ has no attribute ‘flushSched’

**Comment by ijgnd** [comment]
this should be fixed on ankiweb with the upload from 2021-07-05. The relevant commit is [here](https://github.com/ijgnd/anki__rebuild-empty-all-filtered-decks/commit/781e8fc7b6ccfb0065f75599f03abd4925eaaca6). I forgot about answering in this issue.
